version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dependency_file_paths = [
    "chat-backend/",
    "chat-backend/.dependencies/aws-sdk-api/nodejs/",
    "chat-backend/.dependencies/aws-sdk-ddb/nodejs/",
    "chat-backend/.dependencies/aws-sdk-sns/nodejs/",
    "chat-backend/.dependencies/firebase-admin/nodejs/",
    "chat-backend/actions/banreply/",
    "chat-backend/actions/banrequest/",
    "chat-backend/actions/ondisconnect/",
    "chat-backend/actions/register/",
    "chat-backend/actions/switchgroup/",
    "chat-backend/actions/textmessage/",
    "chat-backend/chat-backend-package/",
    "chat-backend/handle-inactive-users/",
    "chat-backend/http/get/status/",
    "chat-backend/http/post/change-group/",
    "chat-backend/http/post/text-message/",
    "chat-backend/http/put/share-profile/",
    "chat-backend/http/put/sign-in/",
    "chat-backend/http/put/sign-up/",
    "chat-backend/manual-setup/",
    "chat-backend/put-firebase-token/",
    "chat-backend/sendmessage/",
    "chat-backend/sendnotification/",
    "chat-backend/storeunreaddata/",
    "chat-backend/switchgroup/",
    "content-moderation/",
    "scripts/",
  ]
  environment = ["nodejs"]
  module_system = "commonjs"
  style_guide = "standard"

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
