version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dependency_file_paths = [
    "chat-backend/",
    "chat-backend/chat-backend-package/",
    "chat-backend/http/delete/unread-data/",
    "chat-backend/http/get/status/",
    "chat-backend/http/get/unread-data/",
    "chat-backend/http/post/change-group/",
    "chat-backend/http/post/download-user/",
    "chat-backend/http/post/text-message/",
    "chat-backend/http/post/upload-user/",
    "chat-backend/http/put/firebase-token/",
    "chat-backend/http/put/reply-ban/",
    "chat-backend/http/put/request-ban/",
    "chat-backend/http/put/sign-in/",
    "chat-backend/http/put/sign-up/",
    "chat-backend/manual-setup/",
    "chat-backend/websocket/authorizer/",
    "chat-backend/websocket/on-connect/",
    "chat-backend/websocket/on-disconnect/",
    "content-moderation/",
    "scripts/",
  ]
  environment = ["nodejs"]
  module_system = "commonjs"
  style_guide = "standard"

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
